name: Vercel Deployment Error Comment

# Triggers when Vercel deployment completes
on:
  deployment_status:

jobs:
  comment-on-failure:
    # Only run when deployment fails
    if: github.event.deployment_status.state == 'failure'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if deployment is from Vercel
        id: check_vercel
        run: |
          if [[ "${{ github.event.deployment_status.environment_url }}" == *"vercel.app"* ]]; then
            echo "is_vercel=true" >> $GITHUB_OUTPUT
          else
            echo "is_vercel=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Get deployment details
        if: steps.check_vercel.outputs.is_vercel == 'true'
        id: get_details
        run: |
          DEPLOYMENT_URL="${{ github.event.deployment_status.target_url }}"
          
          # Extract deployment ID from URL
          DEPLOYMENT_ID=$(echo "$DEPLOYMENT_URL" | grep -oP 'dpl_[a-zA-Z0-9]+' || echo "")
          
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
      
      - name: Fetch Vercel deployment logs
        if: steps.check_vercel.outputs.is_vercel == 'true'
        id: fetch_logs
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          DEPLOYMENT_ID="${{ steps.get_details.outputs.deployment_id }}"
          
          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "error_message=Could not extract deployment ID" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Fetch deployment events/logs
          RESPONSE=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v3/deployments/$DEPLOYMENT_ID/events")
          
          # Extract error messages from logs
          ERROR_LOGS=$(echo "$RESPONSE" | jq -r '.[] | select(.payload.text | contains("Error") or contains("error") or contains("Failed") or contains("failed")) | .payload.text' | head -50)
          
          if [ -z "$ERROR_LOGS" ]; then
            ERROR_LOGS="Deployment failed but no specific error logs were captured. Check the Vercel dashboard for details."
          fi
          
          # Save to file to handle multiline output
          echo "$ERROR_LOGS" > error_logs.txt
      
      - name: Find PR number
        if: steps.check_vercel.outputs.is_vercel == 'true'
        id: find_pr
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.deployment.sha;
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha
            });
            
            if (prs.length > 0) {
              return prs[0].number;
            }
            return null;
      
      - name: Post comment to PR
        if: steps.check_vercel.outputs.is_vercel == 'true' && steps.find_pr.outputs.result != 'null'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const errorLogs = fs.readFileSync('error_logs.txt', 'utf8');
            const prNumber = ${{ steps.find_pr.outputs.result }};
            const deploymentUrl = '${{ steps.get_details.outputs.deployment_url }}';
            
            const commentBody = `## 🚨 Vercel Deployment Failed
            
**Deployment:** [View on Vercel](${deploymentUrl})
**Commit:** ${context.sha.substring(0, 7)}

### Error Details:
\`\`\`
${errorLogs}
\`\`\`

---
<sub>This comment was automatically posted by GitHub Actions when the Vercel deployment failed.</sub>`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
