name: Vercel Deployment Failure Comment

on:
  # This event is triggered by Vercel's GitHub integration when a deployment status changes.
  deployment_status:

jobs:
  handle-vercel-failure:
    # Only run the job if the deployment state is either 'failure' or 'success' 
    # (to delete the previous failure comment). This saves GitHub Actions minutes.
    if: |
      github.event.deployment_status.state == 'failure' ||
      github.event.deployment_status.state == 'success'
    
    runs-on: ubuntu-latest

    steps:
      - name: Check if deployment is from Vercel
        id: check_vercel
        # Vercel deployments typically use 'vercel.app' in the environment URL.
        run: |
          URL="${{ github.event.deployment_status.environment_url }}"
          if [[ "$URL" == *"vercel.app"* ]]; then
            echo "is_vercel=true" >> $GITHUB_OUTPUT
          else
            echo "is_vercel=false" >> $GITHUB_OUTPUT
          fi

      - name: Get deployment details
        if: steps.check_vercel.outputs.is_vercel == 'true'
        id: get_details
        run: |
          # The deployment ID is needed for Vercel API calls
          DEPLOYMENT_ID="${{ github.event.deployment_status.deployment.id }}"
          # target_url is the Vercel preview/deployment URL
          DEPLOYMENT_URL="${{ github.event.deployment_status.target_url }}"
          DEPLOYMENT_STATE="${{ github.event.deployment_status.state }}"
          
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "deployment_state=$DEPLOYMENT_STATE" >> $GITHUB_OUTPUT

      - name: Fetch Vercel logs (only on failure)
        # Only run if it's a Vercel deployment and the state is failure
        if: steps.check_vercel.outputs.is_vercel == 'true' && steps.get_details.outputs.deployment_state == 'failure'
        id: fetch_logs
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          DEPLOYMENT_ID="${{ steps.get_details.outputs.deployment_id }}"

          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "No deployment ID found."
            echo "Deployment failed but the deployment ID was missing." > error_logs.txt
            exit 0
          fi
          
          # Attempt to fetch the last 50 error-related lines from the event stream
          # This requires the VERCEL_TOKEN to have correct permissions.
          # FIX: Removed the extraneous markdown link brackets around the URL.
          RESPONSE=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v2/deployments/$DEPLOYMENT_ID/events")

          # Filter the last 50 log lines that contain error keywords.
          # We use `head -50` to limit the size of the comment.
          ERROR_LOGS=$(echo "$RESPONSE" | jq -r '.[] | select(.payload.text | test("Error|error|Failed|failed|ERR")) | .payload.text' | head -50)

          if [ -z "$ERROR_LOGS" ]; then
            ERROR_LOGS="Deployment failed but no specific error logs were captured via the API. Please check the Vercel dashboard for details."
          fi

          echo "$ERROR_LOGS" > error_logs.txt

      - name: Find PR number associated with the commit
        if: steps.check_vercel.outputs.is_vercel == 'true'
        id: find_pr
        uses: actions/github-script@v7
        with:
          script: |
            // Use the explicit path to the commit SHA from the deployment status event
            const sha = context.payload.deployment_status.deployment.sha;
            
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha
            });
            // Return the first PR number found, or null
            if (prs.length > 0) return prs[0].number;
            return null;

      - name: Post or delete PR comment
        # Only run if it's a Vercel deployment AND we found a PR number
        if: steps.check_vercel.outputs.is_vercel == 'true' && steps.find_pr.outputs.result != 'null'
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.find_pr.outputs.result }}
          DEPLOYMENT_STATE: ${{ steps.get_details.outputs.deployment_state }}
          DEPLOYMENT_URL: ${{ steps.get_details.outputs.deployment_url }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            // Parse environment variables passed from the YAML context
            const prNumber = parseInt(process.env.PR_NUMBER);
            const deploymentUrl = process.env.DEPLOYMENT_URL;
            const commitSha = context.sha.substring(0, 7);
            const state = process.env.DEPLOYMENT_STATE;
            
            const commentHeader = '## 🚨 Vercel Deployment Failed';
            const commentFooter = '<sub>This comment was automatically posted by GitHub Actions when the Vercel deployment failed.</sub>';

            // Find an existing failure comment posted by this bot
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const existing = comments.find(c =>
              c.user.type === 'Bot' && c.body && c.body.includes(commentHeader)
            );

            // --- Failure Logic ---
            if (state === 'failure') {
              const errorLogs = fs.existsSync('error_logs.txt')
                ? fs.readFileSync('error_logs.txt', 'utf8')
                : 'Could not retrieve error logs.'; // Fallback message

              const body = [
                commentHeader,
                '',
                `**Status:** **Failure**`,
                `**Deployment:** [View on Vercel](${deploymentUrl})`,
                `**Commit:** \`${commitSha}\``,
                '',
                '### Error Snippet:',
                // Added 'bash' for syntax highlighting
                '```bash', 
                errorLogs,
                '```',
                '',
                '---',
                commentFooter
              ].join('\n');

              if (existing) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existing.id,
                  body
                });
                console.log(`Updated existing failure comment (#${existing.id}) on PR #${prNumber}`);
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body
                });
                console.log(`Posted new failure comment on PR #${prNumber}`);
              }
              return;
            }

            // --- Success Logic (Delete Comment) ---
            if (state === 'success' && existing) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id
              });
              console.log(`Deleted old failure comment after successful deployment.`);
            }